backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: "assets/img/uploads"

site_url: http://127.0.0.1:4000
logo_url: http://127.0.0.1:4000/images/TU_Logo_kurz_rot_Screen/TU_Logo_kurz_RGB_rot.jpg

collections:
  - name: "post"
    label: "News"
    folder: "content/post"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image", required: false }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", widget: "string" }

  - name: "publications"
    label: "Publications"
    folder: "content/publication"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "authors", label: "Authors", widget: "list" }
      - { name: "date", label: "Publication Date", widget: "date" }
      - { name: "abstract", label: "Abstract", widget: "markdown" }

  - name: "research"
    label: "Research"
    folder: "content/research"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "speaker", label: "Speaker", widget: "string" }
      - { name: "time", label: "Time", widget: "string" }
      - { name: "place", label: "Place", widget: "string" }
      - { name: "abstract", label: "Abstract", widget: "markdown" }
      - { name: "bio", label: "Bio", widget: "markdown" }
  - name: "theses"
    label: "Theses"
    folder: "content/theses"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "last_updated", label: "Last Updated", widget: "datetime" }
      - { name: "status", label: "Status", widget: "select", options: ["Available", "Running", "Completed"] }
      # Add any other fields you need for theses

taxonomies:
  - name: "thesis_status"
    label: "Thesis Status"
    plural: "Thesis Statuses"
    widget: "hidden"
